"use client";

import { useState } from "react";
import { PageShell } from "@/components/system/page-shell";
import { SectionShell } from "@/components/system/section-shell";
import { ThreeLens } from "@/components/artifacts/three-lens";
import { ReactionDecode } from "@/components/artifacts/reaction-decode";
import { ClarifiedOutput } from "@/components/artifacts/clarified-output";

export default function LearnPage() {
  const [input, setInput] = useState("");
  const hasInput = input.trim().length > 0;

  return (
    <PageShell>
      <SectionShell>
        <h1 className="text-3xl font-semibold">Understand the read</h1>
        <p className="text-neutral-500 max-w-2xl">
          Describe a situation and see how the system interprets it.
        </p>
      </SectionShell>

      <SectionShell>
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Describe a moment to understand how it is analyzed..."
          className="w-full border rounded-xl p-4 min-h-[120px]"
        />
      </SectionShell>

      {hasInput && (
        <SectionShell className="space-y-8">
          <ThreeLens
            baseline="This reflects your underlying tendencies."
            now="This highlights what may be active right now."
            relationships="This shows how it may play out between people."
          />

          <ReactionDecode
            pattern="A pattern may be driving the reaction."
            pressure="Pressure can amplify that pattern."
            landing="This may land differently than intended."
            repeat="The loop continues if not recognized."
            response="Recognizing the pattern changes the outcome."
          />

          <ClarifiedOutput
            summary="This output is generated by combining baseline, moment, and relational signals."
            guidance="Use this to understand how the read is formed and how to apply it."
          />
        </SectionShell>
      )}
    </PageShell>
  );
}
